message = input("Say something")
print(type(message))
print(f"Is numeric?\n{message.isnumeric()}")
print(f"Is all whitespaces?\n{message.isspace()}")
print(f"Is in the alphabet?\n{message.isalpha()}")
print(f"Is it alphanumeric?\n{message.isalnum()}")
print(f"Is all characters uppercase?\n{message.isupper()}")
print(f"Is all characters lowercase?\n{message.islower()}")
print(f"Is it capitalized?\n{message.istitle()}")
